### ISSUE TITLE
Create Logo for Hex.Blue

### ISSUE THREAD

**Issue by calvinmorett** [calvinmorett/hexblue#4]
Hex.Blue needs a logo!

Visit the website, develop some ideas and ask to be assigned as a contributor to this issue for further progression of a logo, that can be used as a favicon and as a banner within the site.

The logo should look presentable in grayscale / black and white as well as rgb/cymk color scheme.

Thank you for contributing.

**Comment by jaykesarkar** [comment]
I would like to work on this issue.

**Comment by jaykesarkar** [comment]
Done.

![Hex blue](https://github.com/calvinmorett/hexblue/assets/115918351/f5791d25-6bf8-4d6f-9df6-a40152d33e30)

**Comment by calvinmorett** [comment]
Can there be a black and white version as well?

**Comment by jaykesarkar** [comment]
> Can there be a black and white version as well?

I didn't get it, can you specify what should be black & what should be white. I mean logo or name.

**Comment by calvinmorett** [comment]
The background black and the logomark + text white.

**Comment by jaykesarkar** [comment]
> The background black and the logomark + text white.

Done
![hex blue](https://github.com/calvinmorett/hexblue/assets/115918351/56a73bd4-0673-42cd-b4d0-c7479c912ae1)

**Comment by calvinmorett** [comment]
Thank you for your work!

**Comment by jaykesarkar** [comment]
> Thank you for your work!

You're very welcome, and thank you for giving credit in the README

**Comment by calvinmorett** [comment]
Of course!
